version: '3.7'

services:

  webapi:
    container_name: webapi
    image: webapi
    build:
      context: .
      dockerfile: ./src/Dotnet5.GraphQL.Store.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://*:5001;http://*:5000
    ports:
      - 5000:80
      - 5001:443
    networks:
      - graphqlstore

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "!MyComplexPassword"
      ACCEPT_EULA: "Y"
    networks:
      - graphqlstore
        
networks:
  graphqlstore:
    driver: bridge